name: bukizz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  dots_indicator: ^3.0.0
  carousel_slider: ^4.2.1
  otp_text_field: ^1.1.3
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  curved_navigation_bar: ^1.0.3
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  upi_india: ^3.0.1
  responsive_sizer: ^3.3.0+1
  firebase_database: ^10.4.5
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^16.3.2
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  awesome_snackbar_content: ^0.1.3
  email_auth: ^1.1.1
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-Bold.ttf
        - asset: fonts/Nunito/Nunito-Italic.ttf
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf


  assets:
    - assets/
    - assets/checkout/
    - assets/category/
    - assets/school/
    - assets/payment/
    - assets/onboarding/
    - assets/stationary/
    - assets/uniform/
    - assets/tab icons/
    - assets/school/booksets/
    - assets/cart/
    - assets/images/
    - assets/ecommerce home/
    - assets/ecommerce home/icons/
    - assets/ecommerce home/tab icons/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
